from .profile import Profile
from .education import Education
from .course import Course
from .academic_title import AcademicTitle
from .academic_degree import AcademicDegree
from .institution_degree_type import InstitutionDegreeType
from .institution import Institution
from .language_proficiency import LanguageProficiency
from .language import Language
from .course_provider import CourseProvider
from .educational_profile import EducationalProfile
from .academic_degree_degree import AcademicDegreeDegree
from .academic_title_degree import AcademicTitleDegree
from .specialty import Specialty
from .science import Science
