version: '3'

services:

  postgres:
    image: postgres:15.1-alpine
    container_name: postgresql-prod
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: always
    env_file:
      - .env
    ports:
      - '5410:5432'
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - prod-dev

  sgo-erp:
    platform: linux/amd64
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8001 --log-config log.ini"
    build: .
    image: sgo-erp:v1.0.0
    container_name: sgo-erp-prod
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    networks:
      - prod-dev
    depends_on:
      postgres:
        condition: service_healthy

networks:
  prod-dev:
    driver: bridge
