version: '3'

services:

  postgres-dev-erp:
    image: postgres:15.1-alpine
    container_name: postgresql-dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    env_file:
      - .env
    ports:
      - '5411:5432'
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - backend-erp-sgo

  sgo-erp-dev-erp:
    platform: linux/amd64
    command: bash -c "ruff check . --ignore E712,E711 --exclude ./alembic,__init__.py && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8003 --log-config log.ini --workers ${NUMBER_OF_WORKERS}"
    build: .
    container_name: sgo-erp-dev
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    networks:
      - backend-erp-sgo
    depends_on:
        postgres-dev-erp:
          condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  backend-erp-sgo:
    driver: bridge