version: '3'

services:
  sgo-erp-oracle:
    platform: linux/amd64
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8005 --log-config log.ini --workers ${NUMBER_OF_WORKERS} --reload"
    build: .
    container_name: sgo-erp-oracle
    restart: always
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    networks:
      - sgo-erp-oracle
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  sgo-erp-oracle:
    driver: bridge
