version: '3'

services:

  postgres:
    image: postgres:15.1-alpine
    container_name: postgresql-test
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    env_file:
      - .env
    ports:
      - '5412:5432'
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - backend-dev
  
  sgo-erp:
    platform: linux/amd64
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8002 --log-config log.ini --workers 12"
    build: .
    container_name: sgo-erp-test
    restart: always
    ports:
        - "8002:8002"
    volumes:
      - .:/app  
    networks:
      - backend-dev
    depends_on:
        postgres:
          condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  backend-dev:
      driver: bridge
