from .education import EducationRead, EducationCreate, EducationUpdate
from .academic_degree import AcademicDegreeRead, AcademicDegreeCreate, AcademicDegreeUpdate
from .academic_degree_degree import AcademicDegreeDegreeRead, AcademicDegreeDegreeCreate, AcademicDegreeDegreeUpdate
from .academic_title import AcademicTitleRead, AcademicTitleCreate, AcademicTitleUpdate
from .academic_title_degree import AcademicTitleDegreeRead, AcademicTitleDegreeCreate, AcademicTitleDegreeUpdate
from .course_provider import CourseProviderRead, CourseProviderCreate, CourseProviderUpdate
from .course import CourseRead, CourseCreate, CourseUpdate
from .language_proficiency import LanguageProficiencyRead, LanguageProficiencyCreate, LanguageProficiencyUpdate
from .language import LanguageRead, LanguageCreate, LanguageUpdate
from .institution import InstitutionRead, InstitutionCreate, InstitutionUpdate
from .science import ScienceRead, ScienceCreate, ScienceUpdate
from .specialty import SpecialtyRead, SpecialtyCreate, SpecialtyUpdate
from .institution_degree_type import InstitutionDegreeTypeRead, InstitutionDegreeTypeCreate, InstitutionDegreeTypeUpdate
from .educational_profile import (EducationalProfileRead, EducationalProfileCreate, EducationalProfileUpdate)
