from .education import EducationRead, EducationCreate, EducationUpdate, EducationShortRead
from .academic_degree_degree import AcademicDegreeDegreeRead, AcademicDegreeDegreeCreate, AcademicDegreeDegreeUpdate, AcademicDegreeDegreeReadPagination
from .science import ScienceRead, ScienceCreate, ScienceUpdate
from .specialty import SpecialtyRead, SpecialtyCreate, SpecialtyUpdate, SpecialtyReadPagination
from .academic_degree import AcademicDegreeRead, AcademicDegreeCreate, AcademicDegreeUpdate, AcademicDegreeShorRead
from .academic_title import AcademicTitleRead, AcademicTitleCreate, AcademicTitleUpdate, AcademicTitleShortRead
from .academic_title_degree import AcademicTitleDegreeRead, AcademicTitleDegreeCreate, AcademicTitleDegreeUpdate
from .course_provider import CourseProviderRead, CourseProviderCreate, CourseProviderUpdate, CourseProviderReadPagination
from .course import CourseRead, CourseCreate, CourseUpdate, CourseShortRead
from .language_proficiency import LanguageProficiencyRead, LanguageProficiencyCreate, LanguageProficiencyUpdate
from .language import LanguageRead, LanguageCreate, LanguageUpdate, LanguageReadPagination
from .institution import InstitutionRead, InstitutionCreate, InstitutionUpdate, InstitutionReadPagination
from .institution_degree_type import InstitutionDegreeTypeRead, InstitutionDegreeTypeCreate, InstitutionDegreeTypeUpdate, InstitutionDegreeTypeReadPagination
from .educational_profile import EducationalProfileRead, EducationalProfileCreate, EducationalProfileUpdate
