"""feature: added previous step for hr_document_steps

Revision ID: 03f22dae4b3a
Revises: 35ba84251438
Create Date: 2023-02-09 08:12:25.294417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f22dae4b3a'
down_revision = '35ba84251438'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_document_steps', sa.Column('previous_step_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'hr_document_steps', 'hr_document_steps', ['previous_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hr_document_steps', type_='foreignkey')
    op.drop_column('hr_document_steps', 'previous_step_id')
    # ### end Alembic commands ###
