"""alter_table_hr_documents

Revision ID: 059525451b45
Revises: addc37bbe8ea
Create Date: 2023-02-16 15:56:09.843521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059525451b45'
down_revision = 'addc37bbe8ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_documents', sa.Column('reg_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'hr_documents', ['reg_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hr_documents', type_='unique')
    op.drop_column('hr_documents', 'reg_number')
    # ### end Alembic commands ###
