"""feat (candidates): add tables

Revision ID: 015156a1e346
Revises: f2d361d3fec3
Create Date: 2023-04-04 06:43:18.042369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015156a1e346'
down_revision = 'f2d361d3fec3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_stage_answers', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidate_stage_answers', 'candidate_categories', ['category_id'], ['id'])
    op.alter_column('candidate_stage_infos', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_stage_infos', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'candidate_stage_answers', type_='foreignkey')
    op.drop_column('candidate_stage_answers', 'category_id')
    # ### end Alembic commands ###
