"""empty message

Revision ID: 52a41c1a4bdc
Revises: 48a197e3f201
Create Date: 2023-03-01 10:42:33.264478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a41c1a4bdc'
down_revision = '48a197e3f201'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('badges', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('badges', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('document_function_types', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('document_function_types', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hr_document_steps', sa.Column('jurisdiction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'hr_document_steps', 'jurisdictions', ['jurisdiction_id'], ['id'])
    op.add_column('permissions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permissions', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ranks', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ranks', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_function_types', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_function_types', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('staff_functions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('staff_functions', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('user_functions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_functions', 'function_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('user_stats', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'updated_at')
    op.alter_column('user_functions', 'function_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_functions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('staff_functions', 'updated_at')
    op.drop_column('staff_functions', 'created_at')
    op.drop_column('service_function_types', 'updated_at')
    op.drop_column('service_function_types', 'created_at')
    op.drop_column('ranks', 'updated_at')
    op.drop_column('ranks', 'created_at')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    op.drop_constraint(None, 'hr_document_steps', type_='foreignkey')
    op.drop_column('hr_document_steps', 'jurisdiction_id')
    op.drop_column('document_function_types', 'updated_at')
    op.drop_column('document_function_types', 'created_at')
    op.drop_column('badges', 'updated_at')
    op.drop_column('badges', 'created_at')
    op.drop_table('jurisdictions')
    # ### end Alembic commands ###
