"""feat: added counter to staff_list

Revision ID: 13d9f12c9a8f
Revises: c82a7ec01eaa
Create Date: 2023-06-10 17:08:14.485358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d9f12c9a8f'
down_revision = 'c82a7ec01eaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_lists', sa.Column(
        'changes_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_lists', 'changes_size')
    # ### end Alembic commands ###
