"""feature/hr_vacancies

Revision ID: c2380007ea31
Revises: b6c2329ba373
Create Date: 2023-05-19 08:38:13.928919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2380007ea31'
down_revision = 'b6c2329ba373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_vacancies_requirements',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_vacancies',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('staff_division_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['staff_division_id'], ['staff_divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_vacancy_hr_vacancy_requirements',
    sa.Column('vacancy_id', sa.UUID(), nullable=True),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['hr_vacancies_requirements.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['hr_vacancies.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_vacancy_hr_vacancy_requirements')
    op.drop_table('hr_vacancies')
    op.drop_table('hr_vacancies_requirements')
    # ### end Alembic commands ###
