"""hr_document_template-description-named

Revision ID: bbbd58ffa3ee
Revises: 87263d264688
Create Date: 2023-07-13 12:23:34.902483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbbd58ffa3ee'
down_revision = 'bd90d3894431'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hr_document_templates', 'description',
                    existing_type=postgresql.JSON(
                        none_as_null=True, astext_type=sa.Text()
                    ),
                    nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hr_document_templates', 'description',
                    existing_type=sa.TEXT(),
                    nullable=True,
                    existing_server_default='')
