"""feat (history, equipment): add tables

Revision ID: 1c40e398dc0c
Revises: 0c959d785ed4
Create Date: 2023-04-05 08:20:06.269358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c40e398dc0c'
down_revision = '0c959d785ed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('military_units',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('name_changes',
    sa.Column('name_before', sa.String(), nullable=True),
    sa.Column('name_after', sa.String(), nullable=True),
    sa.Column('name_type', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_army_equipments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_clothing_equipments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_other_equipments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_army_equipment_models',
    sa.Column('type_of_army_equipment_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_of_army_equipment_id'], ['type_army_equipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_clothing_equipment_models',
    sa.Column('type_of_clothing_equipment_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_of_clothing_equipment_id'], ['type_clothing_equipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_other_equipment_models',
    sa.Column('type_of_other_equipment_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_of_other_equipment_id'], ['type_other_equipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_ids',
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('token_status', sa.Enum('RECEIVED', 'LOST', 'NOT_RECEIVED', name='serviceidstatus'), nullable=True),
    sa.Column('id_status', sa.Enum('RECEIVED', 'LOST', 'NOT_RECEIVED', name='serviceidstatus'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_oaths',
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('military_unit_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['military_unit_id'], ['military_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('candidate_stage_answers', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidate_stage_answers', 'candidate_categories', ['category_id'], ['id'])
    op.add_column('equipments', sa.Column('type_of_equipment', sa.String(), nullable=True))
    op.add_column('equipments', sa.Column('type_of_army_equipment_model_id', sa.UUID(), nullable=True))
    op.add_column('equipments', sa.Column('inventory_number', sa.String(), nullable=True))
    op.add_column('equipments', sa.Column('count_of_ammo', sa.BigInteger(), nullable=True))
    op.add_column('equipments', sa.Column('type_of_clothing_equipment_model_id', sa.UUID(), nullable=True))
    op.add_column('equipments', sa.Column('type_of_other_equipment_model_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'equipments', 'type_other_equipment_models', ['type_of_other_equipment_model_id'], ['id'])
    op.create_foreign_key(None, 'equipments', 'type_army_equipment_models', ['type_of_army_equipment_model_id'], ['id'])
    op.create_foreign_key(None, 'equipments', 'type_clothing_equipment_models', ['type_of_clothing_equipment_model_id'], ['id'])
    op.drop_column('equipments', 'name')
    op.drop_column('equipments', 'quantity')
    op.add_column('histories', sa.Column('document_link', sa.TEXT(), nullable=True))
    op.add_column('histories', sa.Column('document_number', sa.String(), nullable=True))
    op.add_column('histories', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('histories', sa.Column('coefficient', sa.Double(), nullable=True))
    op.add_column('histories', sa.Column('percentage', sa.Integer(), nullable=True))
    op.add_column('histories', sa.Column('staff_division_id', sa.UUID(), nullable=True))
    op.add_column('histories', sa.Column('name_of_organization', sa.String(), nullable=True))
    op.add_column('histories', sa.Column('history_name_change_id', sa.UUID(), nullable=True))
    op.add_column('histories', sa.Column('attestation_status', sa.String(), nullable=True))
    op.add_column('histories', sa.Column('characteristic_initiator', sa.String(), nullable=True))
    op.drop_constraint('histories_equipment_id_fkey', 'histories', type_='foreignkey')
    op.create_foreign_key(None, 'histories', 'staff_divisions', ['staff_division_id'], ['id'])
    op.create_foreign_key(None, 'histories', 'name_changes', ['history_name_change_id'], ['id'])
    op.drop_column('histories', 'equipment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('equipment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.create_foreign_key('histories_equipment_id_fkey', 'histories', 'equipments', ['equipment_id'], ['id'])
    op.drop_column('histories', 'characteristic_initiator')
    op.drop_column('histories', 'attestation_status')
    op.drop_column('histories', 'history_name_change_id')
    op.drop_column('histories', 'name_of_organization')
    op.drop_column('histories', 'staff_division_id')
    op.drop_column('histories', 'percentage')
    op.drop_column('histories', 'coefficient')
    op.drop_column('histories', 'experience_years')
    op.drop_column('histories', 'document_number')
    op.drop_column('histories', 'document_link')
    op.add_column('equipments', sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('equipments', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_column('equipments', 'type_of_other_equipment_model_id')
    op.drop_column('equipments', 'type_of_clothing_equipment_model_id')
    op.drop_column('equipments', 'count_of_ammo')
    op.drop_column('equipments', 'inventory_number')
    op.drop_column('equipments', 'type_of_army_equipment_model_id')
    op.drop_column('equipments', 'type_of_equipment')
    op.drop_constraint(None, 'candidate_stage_answers', type_='foreignkey')
    op.drop_column('candidate_stage_answers', 'category_id')
    op.drop_table('user_oaths')
    op.drop_table('service_ids')
    op.drop_table('type_other_equipment_models')
    op.drop_table('type_clothing_equipment_models')
    op.drop_table('type_army_equipment_models')
    op.drop_table('type_other_equipments')
    op.drop_table('type_clothing_equipments')
    op.drop_table('type_army_equipments')
    op.drop_table('name_changes')
    op.drop_table('military_units')
    # ### end Alembic commands ###
