"""init

Revision ID: 461e308e6b57
Revises: 
Create Date: 2023-04-14 01:48:16.429036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '461e308e6b57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_degree_degrees',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_title_degrees',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badge_types',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_essay_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_types',
    sa.Column('is_finite', sa.Boolean(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coolness_types',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_providers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_function_types',
    sa.Column('can_cancel', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_relations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_statuses',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_document_statuses',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution_degree_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jurisdictions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liberations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('military_units',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranks',
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('military_url', sa.TEXT(), nullable=True),
    sa.Column('employee_url', sa.TEXT(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sciences',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_function_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialties',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_divisions',
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_combat_unit', sa.Boolean(), nullable=True),
    sa.Column('leader_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['staff_divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('max_rank_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['max_rank_id'], ['ranks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_units',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('staff_division_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['staff_division_id'], ['staff_divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_document_templates',
                    sa.Column('path', sa.String(length=255), nullable=True),
                    sa.Column('pathKZ', sa.String(length=255), nullable=True),
                    sa.Column('subject_type',
                              sa.Enum('CANDIDATE', 'EMPLOYEE', 'PERSONNEL', 'STAFF', name='subjecttype'),
                              nullable=True),
                    sa.Column('properties', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
                    sa.Column('description', sa.TEXT(), nullable=True, default=''),
                    sa.Column('actions', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('nameKZ', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('maintainer_id', sa.UUID(), nullable=True),
                    sa.Column('is_visible', sa.Boolean(), default=True),
                    sa.ForeignKeyConstraint(['maintainer_id'], ['staff_units.id']),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_foreign_key('staff_divisions_leader_id_fkey', 'staff_divisions', 'staff_units', ['leader_id'], ['id'])
    op.create_table('status_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_army_equipments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_clothing_equipments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_other_equipments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archive_document_function_types',
    sa.Column('can_cancel', sa.Boolean(), nullable=False),
    sa.Column('origin_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['origin_id'], ['document_function_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archive_service_function_types',
    sa.Column('origin_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['origin_id'], ['service_function_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage_questions',
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('question_type', sa.Enum('STRING_TYPE', 'CHOICE_TYPE', 'TEXT_TYPE', 'DOCUMENT_TYPE', 'ESSAY_TYPE', 'SPORT_SCORE_TYPE', 'DROPDOWN_TYPE', name='candidatestagequestiontypeenum'), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('candidate_stage_type_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_stage_type_id'], ['candidate_stage_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.TEXT(), nullable=True),
    sa.Column('call_sign', sa.String(length=255), nullable=True),
    sa.Column('id_number', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('rank_id', sa.UUID(), nullable=True),
    sa.Column('staff_unit_id', sa.UUID(), nullable=False),
    sa.Column('actual_staff_unit_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supervised_by', sa.UUID(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cabinet', sa.String(length=255), nullable=True),
    sa.Column('service_phone_number', sa.String(length=32), nullable=True),
    sa.Column('is_military', sa.Boolean(), nullable=True),
    sa.Column('personal_id', sa.String(length=255), nullable=True),
    sa.Column('iin', sa.String(length=255), nullable=True),
    sa.Column('date_birth', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('last_signed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actual_staff_unit_id'], ['staff_units.id'], ),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ),
    sa.ForeignKeyConstraint(['staff_unit_id'], ['staff_units.id'], ),
    sa.ForeignKeyConstraint(['supervised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sign'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_number'),
    )
    op.create_table('candidates',
    sa.Column('status', sa.Enum('ACTIVE', 'DRAFT', name='candidatestatusenum'), server_default='ACTIVE', nullable=True),
    sa.Column('debarment_reason', sa.String(), nullable=True),
    sa.Column('is_physical_passed', sa.Boolean(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default='0', nullable=True),
    sa.Column('staff_unit_curator_id', sa.UUID(), nullable=True),
    sa.Column('staff_unit_id', sa.UUID(), nullable=True),
    sa.Column('recommended_by', sa.UUID(), nullable=True),
    sa.Column('essay_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['essay_id'], ['candidate_essay_types.id'], ),
    sa.ForeignKeyConstraint(['staff_unit_curator_id'], ['staff_units.id'], ),
    sa.ForeignKeyConstraint(['staff_unit_id'], ['staff_units.id'], ),
    sa.ForeignKeyConstraint(['recommended_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_functions',
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('discriminator', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['document_function_types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['service_function_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_army_equipment_models',
    sa.Column('type_of_army_equipment_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_of_army_equipment_id'], ['type_army_equipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_clothing_equipment_models',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothing_equipment_types_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_clothing_equipments_id', sa.UUID(), nullable=True),
    sa.Column('type_clothing_equipment_models_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['type_clothing_equipments_id'], ['type_clothing_equipments.id'], ),
    sa.ForeignKeyConstraint(['type_clothing_equipment_models_id'], ['type_clothing_equipment_models.id'], ),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_other_equipment_models',
    sa.Column('type_of_other_equipment_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_of_other_equipment_id'], ['type_other_equipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archive_staff_functions',
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('discriminator', sa.String(length=255), nullable=True),
    sa.Column('origin_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['staff_functions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['archive_document_function_types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['archive_service_function_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attestations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badges',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['badge_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage_answers',
    sa.Column('candidate_stage_question_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answer_str', sa.String(), nullable=True),
    sa.Column('answer_bool', sa.Boolean(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('answer', sa.TEXT(), nullable=True),
    sa.Column('document_link', sa.String(), nullable=True),
    sa.Column('candidate_essay_type_id', sa.UUID(), nullable=True),
    sa.Column('is_sport_passed', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_essay_type_id'], ['candidate_essay_types.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['candidate_stage_question_id'], ['candidate_stage_questions.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['candidate_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage_infos',
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'NOT_STARTED', name='candidatestageinfostatusenum'), server_default='NOT_STARTED', nullable=True),
    sa.Column('date_sign', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('candidate_stage_type_id', sa.UUID(), nullable=True),
    sa.Column('is_waits', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['candidate_stage_type_id'], ['candidate_stage_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['contract_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coolnesses',
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['coolness_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipments',
    sa.Column('date_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('document_link', sa.String(), nullable=True),
    sa.Column('type_of_equipment', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type_of_army_equipment_model_id', sa.UUID(), nullable=True),
    sa.Column('inventory_number', sa.String(), nullable=True),
    sa.Column('count_of_ammo', sa.BigInteger(), nullable=True),
    sa.Column('inventory_count', sa.BigInteger(), nullable=True),
    sa.Column('clothing_size', sa.String(), nullable=True),
    sa.Column('clothing_equipment_types_models_id', sa.UUID(), nullable=True),
    sa.Column('type_of_other_equipment_model_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['type_of_army_equipment_model_id'], ['type_army_equipment_models.id'], ),
    sa.ForeignKeyConstraint(['clothing_equipment_types_models_id'], ['clothing_equipment_types_models.id'], ),
    sa.ForeignKeyConstraint(['type_of_other_equipment_model_id'], ['type_other_equipment_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date_since', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_document_steps',
    sa.Column('hr_document_template_id', sa.UUID(), nullable=False),
    sa.Column('staff_function_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_direct_supervisor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hr_document_template_id'], ['hr_document_templates.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_function_id'], ['staff_functions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('name_changes',
    sa.Column('name_before', sa.String(), nullable=True),
    sa.Column('name_after', sa.String(), nullable=True),
    sa.Column('name_type', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalties',
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['penalty_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnal_reserves',
    sa.Column('reserve', sa.Enum('enlisted', 'reserve', name='reserveenum'), nullable=True),
    sa.Column('date_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_link', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privelege_emergencies',
    sa.Column('form', sa.Enum('form1', 'form2', 'form3', name='formenum'), nullable=True),
    sa.Column('date_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommender_users',
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secondments',
    sa.Column('staff_division_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_division_id'], ['staff_divisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_ids',
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('token_status', sa.Enum('RECEIVED', 'LOST', 'NOT_RECEIVED', name='serviceidstatus'), nullable=True),
    sa.Column('id_status', sa.Enum('RECEIVED', 'LOST', 'NOT_RECEIVED', name='serviceidstatus'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_lists',
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_unit_functions',
    sa.Column('staff_unit_id', sa.UUID(), nullable=False),
    sa.Column('staff_function_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['staff_function_id'], ['staff_functions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_unit_id'], ['staff_units.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_unit_id', 'staff_function_id')
    )
    op.create_table('staff_unit_candidate_stage_infos',
    sa.Column('staff_unit_id', sa.UUID(), nullable=True),
    sa.Column('candidate_stage_info_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_stage_info_id'], ['candidate_stage_infos.id'], ),
    sa.ForeignKeyConstraint(['staff_unit_id'], ['staff_units.id'], )
    )
    op.create_table('statuses',
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['status_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_oaths',
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('military_unit_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['military_unit_id'], ['military_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stats',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('physical_training', sa.Integer(), nullable=True),
    sa.Column('fire_training', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('activity', sa.Integer(), nullable=True),
    sa.Column('opinion_of_colleagues', sa.Integer(), nullable=True),
    sa.Column('opinion_of_management', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archive_staff_divisions',
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_combat_unit', sa.Boolean(), nullable=True),
    sa.Column('leader_id', sa.UUID(), nullable=True),
    sa.Column('staff_list_id', sa.UUID(), nullable=False),
    sa.Column('origin_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['origin_id'], ['staff_divisions.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['archive_staff_divisions.id'], ),
    sa.ForeignKeyConstraint(['staff_list_id'], ['staff_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educational_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histories',
    sa.Column('date_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('cancel_document_link', sa.TEXT(), nullable=True),
    sa.Column('confirm_document_link', sa.TEXT(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('document_style', sa.String(), nullable=True),
    sa.Column('date_credited', sa.TIMESTAMP(), nullable=True),
    sa.Column('rank_assigned_by', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('rank_id', sa.UUID(), nullable=True),
    sa.Column('badge_id', sa.UUID(), nullable=True),
    sa.Column('penalty_id', sa.UUID(), nullable=True),
    sa.Column('coefficient', sa.Double(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('emergency_rank_id', sa.UUID(), nullable=True),
    sa.Column('contractor_signer_name', sa.String(), nullable=True),
    sa.Column('contractor_signer_nameKZ', sa.String(), nullable=True),
    sa.Column('staff_division_id', sa.UUID(), nullable=True),
    sa.Column('staff_division_name', sa.String(), nullable=True),
    sa.Column('staff_division_nameKZ', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('coolness_id', sa.UUID(), nullable=True),
    sa.Column('name_of_organization', sa.String(), nullable=True),
    sa.Column('is_credited', sa.Boolean(), nullable=True),
    sa.Column('position_work_experience', sa.String(), nullable=True),
    sa.Column('secondment_id', sa.UUID(), nullable=True),
    sa.Column('name_change_id', sa.UUID(), nullable=True),
    sa.Column('attestation_id', sa.UUID(), nullable=True),
    sa.Column('attestation_status', sa.String(), nullable=True),
    sa.Column('characteristic_initiator_id', sa.UUID(), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=True),
    sa.Column('status_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attestation_id'], ['attestations.id'], ),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['characteristic_initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['coolness_id'], ['coolnesses.id'], ),
    sa.ForeignKeyConstraint(['emergency_rank_id'], ['ranks.id'], ),
    sa.ForeignKeyConstraint(['name_change_id'], ['name_changes.id'], ),
    sa.ForeignKeyConstraint(['penalty_id'], ['penalties.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ),
    sa.ForeignKeyConstraint(['secondment_id'], ['secondments.id'], ),
    sa.ForeignKeyConstraint(['staff_division_id'], ['staff_divisions.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_documents',
    sa.Column('hr_document_template_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('properties', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('reg_number', sa.String(), nullable=True),
    sa.Column('signed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('initialized_by_id', sa.UUID(), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=True),
    sa.Column('last_step_id', sa.UUID(), nullable=True),
    sa.Column('old_history_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hr_document_template_id'], ['hr_document_templates.id'], ),
    sa.ForeignKeyConstraint(['initialized_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_step_id'], ['hr_document_steps.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['hr_document_statuses.id'], ),
    sa.ForeignKeyConstraint(['old_history_id'], ['histories.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['hr_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_number')
    )
    op.create_table('medical_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abroad_travels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=255), nullable=False),
    sa.Column('destination_country_id', sa.UUID(), nullable=False),
    sa.Column('date_from', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('date_to', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('document_link', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('academic_degrees',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('degree_id', sa.UUID(), nullable=True),
    sa.Column('science_id', sa.UUID(), nullable=True),
    sa.Column('specialty_id', sa.UUID(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('assignment_date', sa.DATE(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['academic_degree_degrees.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['educational_profiles.id'], ),
    sa.ForeignKeyConstraint(['science_id'], ['sciences.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_titles',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('degree_id', sa.UUID(), nullable=True),
    sa.Column('specialty_id', sa.UUID(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('assignment_date', sa.DATE(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['academic_title_degrees.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['educational_profiles.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anthropometric_data',
    sa.Column('head_circumference', sa.Integer(), nullable=True),
    sa.Column('shoe_size', sa.Integer(), nullable=True),
    sa.Column('neck_circumference', sa.Integer(), nullable=True),
    sa.Column('shape_size', sa.Integer(), nullable=True),
    sa.Column('bust_size', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['medical_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archive_staff_units',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('staff_division_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actual_user_id', sa.UUID(), nullable=True),
    sa.Column('origin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actual_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['staff_units.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['staff_division_id'], ['archive_staff_divisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('archive_staff_divisions_leader_id_fkey', 'archive_staff_divisions', 'archive_staff_units', ['leader_id'], ['id'])
    op.create_table('biographic_infos',
    sa.Column('place_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('citizenship', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('family_status_id', sa.UUID(), nullable=True),
    sa.Column('residence_address', sa.String(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_status_id'], ['family_statuses.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('course_provider_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_provider_id'], ['course_providers.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['educational_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispensary_registrations',
    sa.Column('initiator', sa.String(), nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['medical_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driving_licenses',
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('category', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date_of_issue', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educations',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('is_military_school', sa.Boolean(), nullable=True),
    sa.Column('specialty_id', sa.UUID(), nullable=True),
    sa.Column('type_of_top', sa.TEXT(), nullable=True),
    sa.Column('document_number', sa.TEXT(), nullable=True),
    sa.Column('date_of_issue', sa.DATE(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('degree_id', sa.UUID(), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['institution_degree_types.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['educational_profiles.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('IIN', sa.String(), nullable=True),
    sa.Column('birthday', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('death_day', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('birthplace', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('relation_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['family_profiles.id'], ),
    sa.ForeignKeyConstraint(['relation_id'], ['family_relations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_user_informations',
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.Enum('O_PLUS', 'O_MINUS', 'A_PLUS', 'A_MINUS', 'B_PLUS', 'B_MINUS', 'AB_PLUS', 'AB_MINUS', name='bloodtype'), nullable=True),
    sa.Column('age_group', sa.Enum('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'FIFTH', 'SIXTH', name='agegroup'), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['medical_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_datas',
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['medical_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_document_equipments',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['hr_documents.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['equipments.id'], )
    )
    op.create_table('hr_document_infos',
    sa.Column('hr_document_step_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('signed_by_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('signed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('hr_document_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True, default=1),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hr_document_id'], ['hr_documents.id'], ),
    sa.ForeignKeyConstraint(['hr_document_step_id'], ['hr_document_steps.id'], ),
    sa.ForeignKeyConstraint(['signed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_document_users',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['hr_documents.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], )
    )
    op.create_table('identification_cards',
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('date_of_issue', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('issued_by', sa.String(), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_proficiencies',
    sa.Column('language_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['educational_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passports',
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('date_of_issue', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polygraph_checks',
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('date_of_issue', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('document_link', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.Column('purchase_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('purchase_type', sa.String(length=255), nullable=True),
    sa.Column('purchase_typeKZ', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['property_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychological_checks',
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('date_of_issue', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('document_link', sa.String(length=255), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_housings',
    sa.Column('type_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('issue_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['property_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_checks',
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('date_of_issue', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('document_link', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_achievements',
    sa.Column('assignment_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sport_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.ForeignKeyConstraint(['sport_type_id'], ['sport_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_degrees',
    sa.Column('assignment_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sport_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.ForeignKeyConstraint(['sport_type_id'], ['sport_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_declarations',
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_financial_infos',
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('housing_payments_iban', sa.String(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_liberations',
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('initiator', sa.String(), nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('liberation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['liberation_id'], ['liberations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['medical_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_vehicles',
    sa.Column('date_from', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('document_link', sa.TEXT(), nullable=True),
    sa.Column('vin_code', sa.String(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('article_number', sa.String(length=255), nullable=False),
    sa.Column('consequence', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_violations',
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('violation_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], )
    )
    op.create_table('family_abroad_travels',
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('abroad_travel_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['abroad_travel_id'], ['abroad_travels.id'], )
    )
    op.create_table('archive_staff_unit_functions',
    sa.Column('staff_unit_id', sa.UUID(), nullable=False),
    sa.Column('staff_function_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['staff_function_id'], ['archive_staff_functions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_unit_id'], ['archive_staff_units.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_unit_id', 'staff_function_id')
    )
    op.create_table('user_liberations_liberations',
    sa.Column('user_liberation_id', sa.UUID(), nullable=True),
    sa.Column('liberation_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['liberation_id'], ['liberations.id'], ),
    sa.ForeignKeyConstraint(['user_liberation_id'], ['user_liberations.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_liberations_liberations')
    op.drop_table('archive_staff_unit_functions')
    op.drop_table('violations')
    op.drop_table('user_vehicles')
    op.drop_table('user_liberations')
    op.drop_table('user_financial_infos')
    op.drop_table('tax_declarations')
    op.drop_table('sport_degrees')
    op.drop_table('sport_achievements')
    op.drop_table('special_checks')
    op.drop_table('service_housings')
    op.drop_table('psychological_checks')
    op.drop_table('properties')
    op.drop_table('polygraph_checks')
    op.drop_table('passports')
    op.drop_table('language_proficiencies')
    op.drop_table('identification_cards')
    op.drop_table('hr_document_users')
    op.drop_table('hr_document_infos')
    op.drop_table('hr_document_equipments')
    op.drop_table('hospital_datas')
    op.drop_table('general_user_informations')
    op.drop_table('families')
    op.drop_table('educations')
    op.drop_table('driving_licenses')
    op.drop_table('dispensary_registrations')
    op.drop_table('courses')
    op.drop_table('biographic_infos')
    op.drop_table('archive_staff_units')
    op.drop_table('anthropometric_data')
    op.drop_table('academic_titles')
    op.drop_table('academic_degrees')
    op.drop_table('abroad_travels')
    op.drop_table('personal_profiles')
    op.drop_table('medical_profiles')
    op.drop_table('hr_documents')
    op.drop_table('histories')
    op.drop_table('family_profiles')
    op.drop_table('educational_profiles')
    op.drop_table('archive_staff_divisions')
    op.drop_table('additional_profiles')
    op.drop_table('user_stats')
    op.drop_table('user_oaths')
    op.drop_table('statuses')
    op.drop_table('staff_unit_functions')
    op.drop_table('staff_lists')
    op.drop_table('service_ids')
    op.drop_table('secondments')
    op.drop_table('recommender_users')
    op.drop_table('profiles')
    op.drop_table('privelege_emergencies')
    op.drop_table('personnal_reserves')
    op.drop_table('penalties')
    op.drop_table('name_changes')
    op.drop_table('hr_document_steps')
    op.drop_table('events')
    op.drop_table('equipments')
    op.drop_table('coolnesses')
    op.drop_table('contracts')
    op.drop_table('candidate_stage_infos')
    op.drop_table('candidate_stage_answers')
    op.drop_table('badges')
    op.drop_table('attestations')
    op.drop_table('archive_staff_functions')
    op.drop_table('users')
    op.drop_table('type_other_equipment_models')
    op.drop_table('type_clothing_equipment_models')
    op.drop_table('type_army_equipment_models')
    op.drop_table('staff_functions')
    op.drop_table('positions')
    op.drop_table('candidates')
    op.drop_table('candidate_stage_questions')
    op.drop_table('archive_service_function_types')
    op.drop_table('archive_document_function_types')
    op.drop_table('type_other_equipments')
    op.drop_table('type_clothing_equipments')
    op.drop_table('type_army_equipments')
    op.drop_table('status_types')
    op.drop_table('staff_units')
    op.drop_table('staff_divisions')
    op.drop_table('sport_types')
    op.drop_table('specialties')
    op.drop_table('service_function_types')
    op.drop_table('sciences')
    op.drop_table('ranks')
    op.drop_table('property_types')
    op.drop_table('penalty_types')
    op.drop_table('military_units')
    op.drop_table('liberations')
    op.drop_table('languages')
    op.drop_table('jurisdictions')
    op.drop_table('institutions')
    op.drop_table('institution_degree_types')
    op.drop_table('hr_document_templates')
    op.drop_table('hr_document_statuses')
    op.drop_table('family_statuses')
    op.drop_table('family_relations')
    op.drop_table('document_function_types')
    op.drop_table('course_providers')
    op.drop_table('countries')
    op.drop_table('coolness_types')
    op.drop_table('contract_types')
    op.drop_table('candidate_stage_types')
    op.drop_table('candidate_essay_types')
    op.drop_table('candidate_categories')
    op.drop_table('badge_types')
    op.drop_table('academic_title_degrees')
    op.drop_table('academic_degree_degrees')
    # ### end Alembic commands ###
