"""feat: add vehicle model 

Revision ID: 68735684d0fe
Revises: 4c811bb0aab0
Create Date: 2023-03-10 14:27:55.107935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68735684d0fe'
down_revision = '4c811bb0aab0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vehicles',
    sa.Column('date_from', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['additional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('user_vehicles')
    # ### end Alembic commands ###
