"""fix(survey): answer

Revision ID: 3da03f49674d
Revises: 5c725b679n5a
Create Date: 2023-07-24 05:04:45.258319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da03f49674d'
down_revision = '5c725b679n5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_option_id_fkey', 'answers', type_='foreignkey')
    op.drop_column('answers', 'option_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('option_id', sa.String(), autoincrement=False, nullable=True))
    op.create_foreign_key('answers_option_id_fkey', 'answers', 'options', ['option_id'], ['id'])
    # ### end Alembic commands ###
