"""survey: add repeat type to survey

Revision ID: 8a239775b16e
Revises: 1004b02fc203
Create Date: 2023-07-20 04:57:50.827819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a239775b16e'
down_revision = '8d265b679e4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('repeat_type', sa.String()))
    op.execute(sa.text("UPDATE surveys " +
                        "SET repeat_type = 'NEVER'")
    )
    op.alter_column('surveys', 'repeat_type',
            existing_type=sa.VARCHAR(),
            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'repeat_type')
    # ### end Alembic commands ###
