"""feature(survey): уencrypt user id

Revision ID: 0b35df671645
Revises: 87263d264688
Create Date: 2023-07-17 06:06:51.058594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b35df671645'
down_revision = '87263d264688'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM options WHERE discriminator IN ('option_grid', 'option_scale')"))
    conn.execute(sa.text("DELETE FROM questions WHERE question_type IN ('SCALE', 'GRID')"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('encrypted_used_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'encrypted_used_id')
    # ### end Alembic commands ###
