"""fix: survey & quiz

Revision ID: c5f49d190077
Revises: bd90d3894431
Create Date: 2023-07-13 11:56:57.501626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5f49d190077'
down_revision = '59ab1232c593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abroad_travels', 'document_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('absent_users', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('answers', 'grid_values')
    op.drop_column('answers', 'scale_value')
    op.drop_column('answers', 'checkbox_grid_values')
    op.drop_constraint('archive_staff_divisions_origin_id_fkey', 'archive_staff_divisions', type_='foreignkey')
    op.create_foreign_key(None, 'archive_staff_divisions', 'staff_divisions', ['origin_id'], ['id'])
    op.drop_column('options', 'min_value')
    op.drop_column('options', 'max_value')
    op.drop_column('options', 'row_position')
    op.drop_column('options', 'column_position')
    op.alter_column('polygraph_checks', 'document_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('positions', 'category_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('psychological_checks', 'document_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('special_checks', 'document_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('special_checks', 'document_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('psychological_checks', 'document_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('positions', 'category_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('polygraph_checks', 'document_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('options', sa.Column('column_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('options', sa.Column('row_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('options', sa.Column('max_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('options', sa.Column('min_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'archive_staff_divisions', type_='foreignkey')
    op.create_foreign_key('archive_staff_divisions_origin_id_fkey', 'archive_staff_divisions', 'staff_divisions', ['origin_id'], ['id'], ondelete='SET NULL')
    op.add_column('answers', sa.Column('checkbox_grid_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('scale_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('grid_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('absent_users', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('abroad_travels', 'document_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
