"""add reason in histories

Revision ID: fea4179cc54c
Revises: aeac42dd6dc1
Create Date: 2023-06-07 12:00:34.626724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fea4179cc54c'
down_revision = 'aeac42dd6dc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archive_staff_units', 'form')
    op.add_column('histories', sa.Column('reason', sa.String(), nullable=True))
    op.alter_column('positions', 'form',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('abroad_travels', 'document_link',
               existing_type=sa.String(length=255),
               nullable=True)
    op.alter_column('polygraph_checks', 'document_link',
               existing_type=sa.String(length=255),
               nullable=True)
    op.alter_column('psychological_checks', 'document_link',
               existing_type=sa.String(length=255),
               nullable=True)
    op.alter_column('special_checks', 'document_link',
               existing_type=sa.String(length=255),
               nullable=True)
    properties = '{"signed_at":{"alias_name":"Дата подписания","alias_nameKZ":"Қол жеткізу күні","type":"read","data_taken":"auto"},"reg_number":{"alias_name":"Регистрационный номер","alias_nameKZ":"Регистрациялық нөмір","type":"read","data_taken":"auto"},"rank":{"alias_name":"Звание субъекта","alias_nameKZ":"Атауы","type":"read","data_taken":"auto","case":{"kz": 1,"ru": 1}},"last_name":{"alias_name":"Фамилия субъекта","alias_nameKZ":"Тегі","type":"read","data_taken":"auto"},"first_name":{"alias_name":"Имя субъекта","alias_nameKZ":"Аты","type":"read","data_taken":"auto"},"father_name":{"alias_name":"Отчество субъекта","alias_nameKZ":"Әкесінің аты","type":"read","data_taken":"auto"},"id_number":{"alias_name":"Идентификационный номер субъекта","alias_nameKZ":"Субъектінің сәйкестендіру нөмірі","type":"read","data_taken":"auto"},"new_position":{"alias_name":"Новая позиция субъекта","alias_nameKZ":"Жаңа позиция","type":"write","data_taken":"dropdown","field_name":"staff_unit"},"department_name":{"alias_name":"Департамент субъекта","alias_nameKZ":"Департаменті","type":"read","data_taken":"auto"},"reason":{"alias_name":"Причина","alias_nameKZ":"Себебі","type":"read","data_taken":"manual","data_type":"string"},"number":{"alias_name":"Процент","alias_nameKZ":"Пайыз","type":"read","data_taken":"manual","data_type":"number"}}'
    actions = '{"args":[{"position_change":{"staff_unit":{"tagname":"new_position"},"percent":{"tagname":"number"},"reason":{"tagname":"reason"}}}]}'
    op.execute(
        f"UPDATE hr_document_templates "
        f"SET properties = '{properties}', actions = '{actions}'"
        f" WHERE name = 'Приказ о назначении';"
    )
    op.drop_column('staff_units', 'form')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_units', sa.Column('form', postgresql.ENUM('form1', 'form2', 'form3', name='formenum'), autoincrement=False, nullable=True))
    op.alter_column('positions', 'form',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('histories', 'reason')
    op.add_column('archive_staff_units', sa.Column('form', postgresql.ENUM('form1', 'form2', 'form3', name='formenum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
