"""Message

Revision ID: 828ecaf073b5
Revises: b6c2329ba373
Create Date: 2023-04-27 08:11:03.616112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828ecaf073b5'
down_revision = 'b6c2329ba373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
