"""new hr_document_templates

Revision ID: dac7288a7141
Revises: 3d09ba117ccc
Create Date: 2023-06-23 07:49:15.526169

"""
import uuid
from alembic import op
from core import Base
from sqlalchemy import text
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac7288a7141'
down_revision = '3d09ba117ccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # get initiator_staff_unit_id the batyrbek staff_unit
    initiator_staff_unit_id = conn.execute(
        text(
            "SELECT id FROM staff_units WHERE id in (SELECT staff_unit_id FROM users WHERE email = 'batyrbek@mail.ru')")
    ).fetchone()[0]
    # get initiator_staff_unit_id the начальник службы staff_unit
    finisher_staff_unit_id = conn.execute(
        text("SELECT id FROM staff_units WHERE position_id in (SELECT id FROM positions WHERE name = 'Начальник Службы')")
    ).fetchone()[0]

    hr_template1_id = uuid.uuid4()
    hr_template2_id = uuid.uuid4()
    # create document templates
    op.bulk_insert(
        Base.metadata.tables['hr_document_templates'],
        [{
            "name": "Приказ о назначении на должность",
            "nameKZ": "Қызметке тағайындау туралы бұйрық",
            "path": "",
            "pathKZ": f"http://193.106.99.68:2287/static/732a700e-d3f5-475c-bfcc-2f5503a101c1.html",
            "subject_type": 'EMPLOYEE',
            'description': "",
            'maintainer_id': initiator_staff_unit_id,
            'is_visible': True,
            "properties": {
                'rank': {
                    'alias_nameKZ': 'Лауазым',
                    'data_taken': 'auto',
                    'type': 'write',
                    'field_name': 'rank',
                    'to_tags': {
                        'foundInText': 'Звание',
                        'titleKZ': 'Лауазым',
                        'isHidden': False,
                        'cases': 0
                    }
                },
                'surname': {
                    'alias_nameKZ': 'Тегі',
                    'data_taken': 'auto',
                    'type': 'write',
                    'field_name': 'surname',
                    'to_tags': {
                        'titleKZ': 'Тегі',
                        'isHidden': False
                    }
                },
                'name': {
                    'alias_nameKZ': 'Аты',
                    'data_taken': 'auto',
                    'type': 'write',
                    'field_name': 'name',
                    'to_tags': {
                        'titleKZ': 'Аты',
                        'isHidden': False
                    }
                },
                'father': {
                    'alias_nameKZ': 'Өкесінің аты',
                    'data_taken': 'auto',
                    'type': 'write',
                    'field_name': 'father_name',
                    'to_tags': {
                        'foundInText': 'Отчество субъекта',
                        'titleKZ': 'Өкесінің аты',
                        'isHidden': False,
                        'cases': 0
                    }
                },
                'officer_number': {
                    'alias_nameKZ': 'Офицерлік нөмер',
                    'data_taken': 'auto',
                    'type': 'write',
                    'field_name': 'officer_number',
                    'to_tags': {
                        'titleKZ': 'Офицерлік нөмер',
                        'isHidden': False
                    }
                },
                'new_position': {
                    'to_tags': {
                        'tagname': 'new_position',
                        'isHidden': False,
                        'titleKZ': 'Жаңа позиция',
                        'idToChange': '1687429650307',
                        'id': '1687429650307',
                        'foundInText': '{{new-departament-name-full}} {{new-upravleniye-name-full}} {{new-otdel-name-full}} {{new-gruppa-name-full}} {{new-job-title}} ({{new-category_name}}) ({{new-za-chet-job-title}})',
                        'action_type': ['position_change']
                    },
                    'alias_name': 'Новая должность',
                    'alias_nameKZ': 'Новая должность',
                    'type': 'write',
                    'data_taken': 'dropdown',
                    'field_name': 'staff_unit',
                    'isHidden': False
                },
                'posiiton_name': {
                    'alias_nameKZ': 'Позиция',
                    'data_taken': 'auto',
                    'type': 'write',
                    'field_name': 'position',
                    'to_tags': {
                        'titleKZ': 'Позиция',
                        'isHidden': False
                    }
                },
                'reason': {
                    'to_tags': {
                        'tagname': 'reason',
                        'isHidden': False,
                        'titleKZ': 'Себебі',
                        'idToChange': '1687429650310',
                        'id': '1687429650310',
                        'foundInText': '{{reason-for-percent}}',
                        'action_type': ['position_change']
                    },
                    'alias_name': 'Причина надбавки',
                    'alias_nameKZ': 'Причина надбавки',
                    'type': 'read',
                    'data_taken': 'manual',
                    'data_type': 'string',
                    'isHidden': False
                },
                'percentage': {
                    'to_tags': {
                        'tagname': 'percentage',
                        'isHidden': False,
                        'titleKZ': 'Пайыз',
                        'idToChange': '1687429650311',
                        'id': '1687429650311',
                        'foundInText': False,
                        'action_type': ['position_change']
                    },
                    'alias_name': 'Процент надбавки',
                    'alias_nameKZ': 'Процент надбавки',
                    'type': 'read',
                    'data_taken': 'manual',
                    'data_type': 'number',
                    'isHidden': False
                    }
            },
            'actions': {'args': [
                    {
                        'position_change': {
                            'staff_unit': {
                                'tagname': 'new_position',
                                'alias_name': 'Новая должность',
                                'alias_nameKZ': 'Жаңа қызмет атауы'
                            },
                            'percent': {
                                'tagname': 'percentage',
                                'alias_name': 'Процент надбавки',
                                'alias_nameKZ': 'Қосымша пайыз'
                            },
                            'reason': {
                                'tagname': 'reason',
                                'alias_name': 'Причина надбавки',
                                'alias_nameKZ': 'Қосымша пайыздың себебі'
                            }
                        }
                    }
                ]
            },
            'id': hr_template1_id
        }, {
            "name": "Приказ о зачислении на службу сотрудника",
            "nameKZ": "Қызметкерді қызметке қабылдау бұйрығы",
            "path": "",
            "pathKZ": "http://193.106.99.68:2287/static/498662e9-bc52-40ad-a6ff-2a2649a19bd7.html",
            "subject_type": 'CANDIDATE',
            'description': "",
            'maintainer_id': initiator_staff_unit_id,
            'is_visible': True,
            "properties": {
                        'surname': {
                        'alias_nameKZ': '\u0422\u0435\u0433\u0456',
                        'data_taken': 'auto',
                        'type': 'write',
                        'field_name': 'surname',
                        'to_tags': {
                            'titleKZ': '\u0422\u0435\u0433\u0456',
                            'isHidden': 'false'
                            }
                        },
                        'name': {
                        'alias_nameKZ': '\u0410\u0442\u044b',
                        'data_taken': 'auto',
                        'type': 'write',
                        'field_name': 'name',
                        'to_tags': {
                            'titleKZ': '\u0410\u0442\u044b',
                            'isHidden': False
                            }
                        },
                        'father': {
                            'alias_nameKZ': '\u04d8\u043a\u0435\u0441\u0456\u043d\u0456\u04a3 \u0430\u0442\u044b',
                            'data_taken': 'auto',
                            'type': 'write',
                            'field_name': 'father_name',
                            'to_tags': {
                                'foundInText': '\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e \u0441\u0443\u0431\u044a\u0435\u043a\u0442\u0430',

                                'titleKZ': '\u04d8\u043a\u0435\u0441\u0456\u043d\u0456\u04a3 \u0430\u0442\u044b',
                                'isHidden': False,
                                'cases': 0
                            }
                        },
                        'contract': {
                            'to_tags': {
                                'tagname': 'contract',
                                'titleKZ': '\u041a\u043e\u043d\u0442\u0440\u0430\u043a\u0442',
                                'idToChange': '1687429527959',
                                'id': '1687429527959',
                                'foundInText': '{{contract - term}}',
                                'isHidden': False,
                                'cases': 0,
                                'action_type': '[renew_contract]'
                            },
                            'alias_name': '\u041a\u043e\u043d\u0442\u0440\u0430\u043a\u0442',
                            'alias_nameKZ': '\u041a\u043e\u043d\u0442\u0440\u0430\u043a\u0442',
                            'type': 'write',
                            'data_taken': 'dropdown',
                            'field_name': 'contracts',
                            'isHidden': False

                            },
                        'new_rank_name': {
                            'alias_nameKZ': '\u0416\u0430\u04a3\u0430 \u043b\u0430\u0443\u0430\u0437\u044b\u043c',
                            'data_taken': 'dropdown',
                            'type': 'write',
                            'field_name': 'rank',
                            'to_tags': {
                                'titleKZ': '\u0416\u0430\u04a3\u0430 \u043b\u0430\u0443\u0430\u0437\u044b\u043c',
                                'directory': 'rank',
                                'isHidden': 'false'}
                        },
                        'new_position': {
                            'alias_nameKZ': '\u0416\u0430\u04a3\u0430 \u043f\u043e\u0437\u0438\u0446\u0438\u044f',
                            'data_taken': 'dropdown',
                            'type': 'write',
                            'field_name': 'staff_unit',
                            'to_tags': {
                                'titleKZ': '\u0416\u0430\u04a3\u0430 \u043f\u043e\u0437\u0438\u0446\u0438\u044f',
                                'directory': 'staff_unit',
                                'isHidden': 'false'}
                            }
            },
            'actions':  {'args': [
                {
                    'renew_contract': {
                        'contract': {
                            'tagname': 'contract',
                            'alias_name': '\u041a\u043e\u043d\u0442\u0440\u0430\u043a\u0442',
                            'alias_nameKZ': '\u041a\u043e\u043d\u0442\u0440\u0430\u043a\u0442'
                        }
                    }
                }
            ]
            },
            'id': hr_template2_id
        }
    ])

    document_function_id1 = uuid.uuid4()
    document_function_id2 = uuid.uuid4()
    document_function_id3 = uuid.uuid4()
    document_function_id4 = uuid.uuid4()

    # get jurisdiction
    jurisdiction_id = conn.execute(
        text("SELECT id FROM jurisdictions WHERE name = 'Вся служба'")
    ).fetchone()[0]

    # get document_function_type Инициатор
    initiator_id = conn.execute(
        text("SELECT id FROM document_function_types WHERE name = 'Инициатор'")
    ).fetchone()[0]

    # get document_function_type Утверждающий
    finisher_id = conn.execute(
        text("SELECT id FROM document_function_types WHERE name = 'Утверждающий'")
    ).fetchone()[0]

    # create staff_functions
    op.bulk_insert(
        Base.metadata.tables['staff_functions'],
        [
            {
                'id': document_function_id1,
                'hours_per_week': 3,
                'discriminator': 'document_staff_function',
                'name': 'Инициатор приказа о назначении на должность',
                'nameKZ': 'Қызметке тағайындау туралы бұйрығының бастаушысы',
                'jurisdiction_id': jurisdiction_id,
                'priority': 1,
                'role_id': initiator_id
            },
            {
                'id': document_function_id2,
                'hours_per_week': 3,
                'discriminator': 'document_staff_function',
                'name': 'Утверждающий приказа о назначении на должность',
                'nameKZ': 'Қызметке тағайындау туралы бұйрығының бекітушісі',
                'jurisdiction_id': jurisdiction_id,
                'priority': 100,
                'role_id': finisher_id
            },
            {
                'id': document_function_id3,
                'hours_per_week': 3,
                'discriminator': 'document_staff_function',
                'name': 'Инициатор приказа о зачислении на службу сотрудника',
                'nameKZ': 'Кәдеге жарату туралы бұйрығының бастаушысы',
                'jurisdiction_id': jurisdiction_id,
                'priority': 1,
                'role_id': initiator_id
            },
            {
                'id': document_function_id4,
                'hours_per_week': 3,
                'discriminator': 'document_staff_function',
                'name': 'Утверждающий приказа о выводе в распоряжение',
                'nameKZ': 'Қызметкерді қызметке қабылдау бұйрығының бекітушісі',
                'jurisdiction_id': jurisdiction_id,
                'priority': 100,
                'role_id': finisher_id
            },
        ])
    # bond staff_functions with staff units
    op.bulk_insert(
        Base.metadata.tables['staff_unit_functions'],
        [
            {
                'staff_function_id': document_function_id1,
                'staff_unit_id': initiator_staff_unit_id
            },
            {
                'staff_function_id': document_function_id2,
                'staff_unit_id': finisher_staff_unit_id
            },
            {
                'staff_function_id': document_function_id3,
                'staff_unit_id': initiator_staff_unit_id
            },
            {
                'staff_function_id': document_function_id4,
                'staff_unit_id': finisher_staff_unit_id
            }
        ])

    step_id1 = uuid.uuid4()
    step_id2 = uuid.uuid4()
    step_id2_1 = uuid.uuid4()
    step_id2_2 = uuid.uuid4()

    op.bulk_insert(
        Base.metadata.tables['hr_document_steps'],
        [
            {
                'hr_document_template_id': hr_template1_id,
                'previous_step_id': None,
                'staff_function_id': document_function_id1,
                'id': step_id1
            },
            {
                'hr_document_template_id': hr_template1_id,
                'previous_step_id': step_id1,
                'staff_function_id': document_function_id2,
                'id': step_id2
            },
            {
                'hr_document_template_id': hr_template2_id,
                'previous_step_id': None,
                'staff_function_id': document_function_id3,
                'id': step_id2_1
            },
            {
                'hr_document_template_id': hr_template2_id,
                'previous_step_id': step_id2_1,
                'staff_function_id': document_function_id4,
                'id': step_id2_2
            }
        ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
