"""staff_list status

Revision ID: c82a7ec01eaa
Revises: 78d952cfbaa0
Create Date: 2023-06-10 15:41:38.874547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82a7ec01eaa'
down_revision = '78d952cfbaa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_lists', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_lists', 'status')
    # ### end Alembic commands ###
