"""feature/added_state_body_table

Revision ID: 376eb853da7a
Revises: 576296a7cdac
Create Date: 2023-06-04 11:24:02.379360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376eb853da7a'
down_revision = '3e8266d38b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_bodies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nameKZ', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('secondments', sa.Column('state_body_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'secondments', 'state_bodies', ['state_body_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'secondments', type_='foreignkey')
    op.drop_column('secondments', 'state_body_id')
    op.drop_table('state_bodies')
    # ### end Alembic commands ###
