"""candidates

Revision ID: a3bed1d83c94
Revises: f2d361d3fec3
Create Date: 2023-04-03 05:30:43.825504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bed1d83c94'
down_revision = 'f2d361d3fec3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_essay_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage_questions',
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('candidate_stage_type_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_stage_type_id'], ['candidate_stage_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage_infos',
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_sign', sa.TIMESTAMP(), nullable=True),
    sa.Column('candidate_stage_type_id', sa.UUID(), nullable=True),
    sa.Column('staff_unit_coordinate_id', sa.UUID(), nullable=True),
    sa.Column('is_waits', sa.Boolean(), nullable=True),
    sa.Column('candidate_stage_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_stage_id'], ['candidate_stages.id'], ),
    sa.ForeignKeyConstraint(['candidate_stage_type_id'], ['candidate_stage_types.id'], ),
    sa.ForeignKeyConstraint(['staff_unit_coordinate_id'], ['staff_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('staff_unit_curator_id', sa.UUID(), nullable=True),
    sa.Column('staff_unit_id', sa.UUID(), nullable=True),
    sa.Column('candidate_stage_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_stage_id'], ['candidate_stages.id'], ),
    sa.ForeignKeyConstraint(['staff_unit_curator_id'], ['staff_units.id'], ),
    sa.ForeignKeyConstraint(['staff_unit_id'], ['staff_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage_answers',
    sa.Column('candidate_stage_question_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answer_str', sa.String(), nullable=True),
    sa.Column('answer_bool', sa.Boolean(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('answer', sa.TEXT(), nullable=True),
    sa.Column('document_link', sa.String(), nullable=True),
    sa.Column('candidate_essay_type_id', sa.UUID(), nullable=True),
    sa.Column('is_sport_passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_essay_type_id'], ['candidate_essay_types.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['candidate_stage_question_id'], ['candidate_stage_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('educations', 'is_military_school',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hr_document_statuses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_liberations_liberations', 'user_liberation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_liberations_liberations', 'liberation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_liberations_liberations', 'liberation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_liberations_liberations', 'user_liberation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('hr_document_statuses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('educations', 'is_military_school',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('candidate_stage_answers')
    op.drop_table('candidates')
    op.drop_table('candidate_stage_infos')
    op.drop_table('candidate_stage_questions')
    op.drop_table('candidate_stages')
    op.drop_table('candidate_stage_types')
    op.drop_table('candidate_essay_types')
    # ### end Alembic commands ###
