"""feature: added education table

Revision ID: 33853d366eba
Revises: 58f2865b2587
Create Date: 2023-03-08 23:03:38.789070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33853d366eba'
down_revision = '58f2865b2587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_degree_degrees',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('academic_title_degrees',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('course_providers',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('institution_degree_types',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('institutions',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('languages',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sciences',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('specialties',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('educational_profiles',
                    sa.Column('profile_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('academic_degrees',
                    sa.Column('profile_id', sa.UUID(), nullable=True),
                    sa.Column('degree_id', sa.UUID(), nullable=True),
                    sa.Column('science_id', sa.UUID(), nullable=True),
                    sa.Column('specialty_id', sa.UUID(), nullable=True),
                    sa.Column('document_number', sa.String(), nullable=True),
                    sa.Column('document_link', sa.TEXT(), nullable=True),
                    sa.Column('assignment_date', sa.DATE(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['degree_id'], ['academic_degree_degrees.id'], ),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['educational_profiles.id'], ),
                    sa.ForeignKeyConstraint(['science_id'], ['sciences.id'], ),
                    sa.ForeignKeyConstraint(
                        ['specialty_id'], ['specialties.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('academic_titles',
                    sa.Column('profile_id', sa.UUID(), nullable=True),
                    sa.Column('degree_id', sa.UUID(), nullable=True),
                    sa.Column('specialty_id', sa.UUID(), nullable=True),
                    sa.Column('document_number', sa.String(), nullable=True),
                    sa.Column('document_link', sa.TEXT(), nullable=True),
                    sa.Column('assignment_date', sa.DATE(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['degree_id'], ['academic_title_degrees.id'], ),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['educational_profiles.id'], ),
                    sa.ForeignKeyConstraint(
                        ['specialty_id'], ['specialties.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('courses',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('profile_id', sa.UUID(), nullable=True),
                    sa.Column('course_provider_id', sa.UUID(), nullable=True),
                    sa.Column('start_date', sa.DATE(), nullable=True),
                    sa.Column('end_date', sa.DATE(), nullable=True),
                    sa.Column('document_link', sa.TEXT(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['course_provider_id'], [
                        'course_providers.id'], ),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['educational_profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('educations',
                    sa.Column('profile_id', sa.UUID(), nullable=True),
                    sa.Column('start_date', sa.DATE(), nullable=True),
                    sa.Column('end_date', sa.DATE(), nullable=True),
                    sa.Column('institution_id', sa.UUID(), nullable=True),
                    sa.Column('degree_id', sa.UUID(), nullable=True),
                    sa.Column('document_link', sa.TEXT(), nullable=True),
                    sa.Column('specialty_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['degree_id'], ['institution_degree_types.id'], ),
                    sa.ForeignKeyConstraint(['institution_id'], [
                                            'institutions.id'], ),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['educational_profiles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('is_military_school', sa.Boolean(),
                              nullable=False, server_default=sa.text('false')),
                    sa.ForeignKeyConstraint(
                        ['specialty_id'], ['specialties.id'],),
                    sa.Column('type_of_top', sa.TEXT(), nullable=True),
                    sa.Column('document_number', sa.TEXT(), nullable=True),
                    sa.Column('date_of_issue', sa.DATE(), nullable=True),
                    )
    op.create_table('language_proficiencies',
                    sa.Column('level', sa.Integer(), nullable=True),
                    sa.Column('language_id', sa.UUID(), nullable=True),
                    sa.Column('profile_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['language_id'], ['languages.id'], ),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['educational_profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('educations', 'is_military_school',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text('false'))
    op.alter_column('hr_document_statuses', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('user_liberations_liberations', 'user_liberation_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('user_liberations_liberations', 'liberation_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_proficiencies')
    op.drop_table('educations')
    op.drop_table('courses')
    op.drop_table('academic_titles')
    op.drop_table('academic_degrees')
    op.drop_table('educational_profiles')
    op.drop_table('specialties')
    op.drop_table('sciences')
    op.drop_table('languages')
    op.drop_table('institutions')
    op.drop_table('institution_degree_types')
    op.drop_table('course_providers')
    op.drop_table('academic_title_degrees')
    op.drop_table('academic_degree_degrees')
    # ### end Alembic commands ###
