"""feature: added signed_at in hr_document_infos

Revision ID: 0a1753e07f76
Revises: aff15fa0fe16
Create Date: 2023-02-23 15:48:48.324760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1753e07f76'
down_revision = 'aff15fa0fe16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_document_infos', sa.Column('signed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_document_infos', 'signed_at')
    # ### end Alembic commands ###
