"""staff_division_nullable in staff_units

Revision ID: 78d952cfbaa0
Revises: c4e67b3596aa
Create Date: 2023-06-10 12:12:26.462254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d952cfbaa0'
down_revision = 'c4e67b3596aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_units', 'staff_division_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_units', 'staff_division_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
