"""staff_function_is_active

Revision ID: 1d8fcb94d7c9
Revises: 13d9f12c9a8f
Create Date: 2023-06-12 09:19:26.750749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8fcb94d7c9'
down_revision = '13d9f12c9a8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_functions', sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
    op.execute(
        f"UPDATE staff_functions "
        f"SET is_active = TRUE"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_functions', 'is_active')
    # ### end Alembic commands ###
