"""fix: document_type_id -> document_template_id

Revision ID: 2241314540d4
Revises: 03f22dae4b3a
Create Date: 2023-02-09 09:52:01.904400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2241314540d4'
down_revision = '03f22dae4b3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('events', 'desciption')
    op.add_column('hr_documents', sa.Column('hr_document_template_id', sa.UUID(), nullable=True))
    op.drop_constraint('hr_documents_document_type_id_fkey', 'hr_documents', type_='foreignkey')
    op.create_foreign_key(None, 'hr_documents', 'hr_document_templates', ['hr_document_template_id'], ['id'])
    op.drop_column('hr_documents', 'document_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_documents', sa.Column('document_type_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hr_documents', type_='foreignkey')
    op.create_foreign_key('hr_documents_document_type_id_fkey', 'hr_documents', 'hr_document_templates', ['document_type_id'], ['id'])
    op.drop_column('hr_documents', 'hr_document_template_id')
    op.add_column('events', sa.Column('desciption', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
