"""feature: added assocication

Revision ID: 2fd056e36e56
Revises: 72477f414cb6
Create Date: 2023-02-20 09:12:36.330342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd056e36e56'
down_revision = '72477f414cb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_groups',
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], )
    )
    op.add_column('hr_documents', sa.Column('signed_at', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_documents', 'signed_at')
    op.drop_table('position_groups')
    # ### end Alembic commands ###
