"""fix: middle_name -> father_name

Revision ID: 35ba84251438
Revises: bb417d692dcc
Create Date: 2023-02-09 08:01:38.359121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35ba84251438'
down_revision = 'bb417d692dcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('equipments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('groups', sa.Column('desciption', sa.TEXT(), nullable=True))
    op.add_column('groups', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('groups', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hr_document_infos', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hr_document_infos', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hr_document_steps', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hr_document_steps', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('positions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('positions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column("users", "middle_name", new_column_name="father_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "father_name", new_column_name="middle_name")
    op.drop_column('positions', 'updated_at')
    op.drop_column('positions', 'created_at')
    op.drop_column('hr_document_steps', 'updated_at')
    op.drop_column('hr_document_steps', 'created_at')
    op.drop_column('hr_document_infos', 'updated_at')
    op.drop_column('hr_document_infos', 'created_at')
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'desciption')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('equipments', 'updated_at')
    op.drop_column('equipments', 'created_at')
    # ### end Alembic commands ###
