"""insert data

Revision ID: 512b89e2ce36
Revises: f9f7edaa69b6
Create Date: 2023-02-09 12:52:18.607053

"""
import uuid

from alembic import op
import sqlalchemy as sa

from core import configs, Base


# revision identifiers, used by Alembic.
revision = '512b89e2ce36'
down_revision = 'f9f7edaa69b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    group_id = str(uuid.uuid4())

    op.bulk_insert(
        Base.metadata.tables['groups'], 
        [{
            'id': group_id, 
            'parent_group_id':None, 
            'name': 'administrators',
        }]
    )

    position_id = str(uuid.uuid4())

    op.bulk_insert(
        Base.metadata.tables['positions'],
        [{
            'id': position_id,
            'name': 'Admin',
            'max_rank_id': None
        }]
    )

    op.bulk_insert(
        Base.metadata.tables['users'],
        [{
            'id': str(uuid.uuid4()),
            'email': 'admin@mail.com',
            'password': '$2b$12$vhg69KJxWiGgetoLxGRvie3VxElPt45i4ELJiE/V2qOj30X3c3.7m',
            'first_name': 'admin',
            'last_name': 'adminov',
            'father_name': 'adminuly',
            'group_id': group_id,
            'position_id': position_id,
            'call_sign': 'killeradmin',
            'id_number': '123456789',
            'phone_number': '+77771234789',
            'address': 'Mangilik Yel, 1'
        }]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
