"""feature: added badges

Revision ID: 640d11ada869
Revises: 456eabbe1c47
Create Date: 2023-02-07 15:23:25.608073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '640d11ada869'
down_revision = '456eabbe1c47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_badges',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('badge_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('hr_documents', sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('users', sa.Column('rank_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'users', 'ranks', ['rank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'rank_id')
    op.drop_column('hr_documents', 'due_date')
    op.drop_table('users_badges')
    op.drop_table('ranks')
    op.drop_table('badges')
    # ### end Alembic commands ###
