"""feature: added document reference in hr_document_infos

Revision ID: 70354627c426
Revises: ace37bbadeb7
Create Date: 2023-02-08 10:38:23.997082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70354627c426'
down_revision = 'ace37bbadeb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_document_infos', sa.Column('hr_document_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'hr_document_infos', 'hr_documents', ['hr_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hr_document_infos', type_='foreignkey')
    op.drop_column('hr_document_infos', 'hr_document_id')
    # ### end Alembic commands ###
