"""feature: added status_till to user

Revision ID: 72477f414cb6
Revises: 9f7966ef0187
Create Date: 2023-02-17 15:36:31.723933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72477f414cb6'
down_revision = '9f7966ef0187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_till', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status_till')
    # ### end Alembic commands ###
