"""Insert initial data

Revision ID: bb417d692dcc
Revises: 70354627c426
Create Date: 2023-02-08 11:28:33.900366

"""
import uuid

from alembic import op
import sqlalchemy as sa

from core import configs, Base

# revision identifiers, used by Alembic.
revision = 'bb417d692dcc'
down_revision = '70354627c426'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    group_id = str(uuid.uuid4())
    
    op.bulk_insert(
        Base.metadata.tables['groups'], 
        [{
            'id': group_id, 
            'parent_group_id':None, 
            'name': 'administrators',
        }]
    )
    
    op.bulk_insert(
        Base.metadata.tables['users'],
        [{
            'id': str(uuid.uuid4()),
            'email': 'admin@mail.com',
            'password': '$2b$12$vhg69KJxWiGgetoLxGRvie3VxElPt45i4ELJiE/V2qOj30X3c3.7m',
            'first_name': 'admin',
            'last_name': 'adminov',
            'middle_name': 'adminuly',
            'group_id': group_id,
            'call_sign': 'killeradmin',
            'id_number': '123456789',
            'phone_number': '+77771234789',
            'address': 'Mangilik Yel, 1'
        }]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
