"""feat: added order for rank, and details to documents

Revision ID: f1e92f92a36b
Revises: addc37bbe8ea
Create Date: 2023-02-13 07:27:46.788785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1e92f92a36b'
down_revision = 'addc37bbe8ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_document_templates', sa.Column('details', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.add_column('hr_documents', sa.Column('details', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.add_column('ranks', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranks', 'order')
    op.drop_column('hr_documents', 'details')
    op.drop_column('hr_document_templates', 'details')
    # ### end Alembic commands ###
