from .candidate import router as candidate_router
from .candidate_stage_info import router as candidate_stage_info_router
from .candidate_stage_question_type import router as candidate_stage_question_type_router
from .candidate_stage_question import router as candidate_stage_question_router
from .candidate_essay_type import router as candidate_essay_type_router
from .candidate_stage_type import router as candidate_stage_type_router
from .candidate_stage_answer import router as candidate_stage_answer_router
