### Authorization by token, part 1. Zhasulan.
POST http://localhost:8002/api/v1/auth/login
Content-Type: application/json

{
  "email": "zhasulan@mail.ru",
  "password": "123456"
}


> {% client.global.set("auth_token1", response.body.access_token); %}

### Authorization by token, part 2. Beksundet.
POST http://localhost:8002/api/v1/auth/login
Content-Type: application/json

{
  "email": "beksundet@mail.ru",
  "password": "123456"
}


> {% client.global.set("auth_token2", response.body.access_token); %}
