from .family_status import router as family_status_router
from .biographic_info import router as biographic_info_router
from .driving_license import router as driving_license_router
from .identification_card import router as identification_card_router
from .passport import router as passport_router
from .personal_profile import router as personal_profile_router
from .sport_achievement import router as sport_achievement_router
from .sport_degree import router as sport_degree_router
from .tax_declaration import router as tax_declaration_router
from .user_financial_info import router as user_financial_info_router
from .sport_type import router as sport_type_router
